### PR TITLE
Issue 189

### PR DESCRIPTION
**Pull request by o-smirnov**
Please review and merge #207 first, as this is based off that branch.

Adds bindings of non-current paths into singularity, fixing #189 which tripped up @Athanaseus a few times.

Also adds ``access_parent_dir`` and ``write_parent_dir`` fields to Parameter. I quickly realized this was needed for "funny" stuff like CASA flagman (because if it's accessing ``foo/bar.MS``, it also needs access to ``foo/`` itself, so it can create the flagversions table alongside the MS).

### CODE REVIEW

**Comment by o-smirnov** [comment]
Do not merge yet -- see a potential bug.

**Comment by o-smirnov** [comment]
OK seems fine now. But let my recipe run on ilifu for a few more steps to make sure the various directory bindings work as intended.

**Comment by sphemakh** [comment]
Could you also add this test; the file is empty? tests/stimela_tests/test_slurm_config.yml

**Comment by o-smirnov** [comment]
> Could you also add this test; the file is empty? tests/stimela_tests/test_slurm_config.yml

It's empty by design. The user can replace it with a non-empty config file to specify non-default slurm options. We don't have an ``_incude_if_exists`` statement, so it's easier to have an empty file.

**Comment by o-smirnov** [comment]
A few more small fixes incoming... let me run an E2E workflow on ilifu before we merge (and maybe wait for @Athanaseus to finish his test on the pleiades cluster).

**Comment by o-smirnov** [comment]
OK, I'm happy with how it works. All filesystems appear to be mounting correctly. @Athanaseus or @SpheMakh please review and merge. I'll start other fixes on a branch off this one.

**Review by Athanaseus — DISMISSED** [review]

**Review by Athanaseus — DISMISSED** [review]

**Comment by o-smirnov** [comment]
@Athanaseus looks like you reviewed, then cancelled your review -- what's up?

**Review by Athanaseus — DISMISSED** [review]

**Comment by Athanaseus** [comment]
When I approve, it does exactly that. Not sure why.
`@Athanaseus dismissed review on this pull request.`

**Review by Athanaseus — DISMISSED** [review]

**Comment by Athanaseus** [comment]
ok i see now, a file changed, and GitHub won't let me approve without reviewing it.

**Comment by o-smirnov** [comment]
That's odd, my last commit was yesterday, so why is it dismissing your review today? Could you please try approving again?

**Review by Athanaseus — DISMISSED** [review]
LGTM!

**Comment by o-smirnov** [comment]
OK I think the review cancellation is a github bug. I'll force-merge.

**Pull request merged**
