### PR TITLE
make Py11 compliant

### PR DESCRIPTION
**Pull request by SpheMakh**
- Add `basetypes.EmptyClassDefault()` method because `dataclasses` in python 3.11 cannot have mutable (classes in this case) as default values. Updated all the class defaults I could fine.  It may be worth considering a 
```python
def __default__(self): 
    return dataclass.field(default_factory=self)
```
 method to our dataclasses then using ` foo: Bar = Bar.__default__()` when setting defaults.

- Save CASA code in a `tempfile` instead of parsing a multi-line code string; this did not work for me.

### CODE REVIEW

**Review by o-smirnov — COMMENTED** [review]
One last thing @SpheMakh -- have you tried this with CASA<6 (i.e. python2 based)? Just to make sure that code still runs.

**Comment by o-smirnov** [comment]
Reminder @SpheMakh -- could you please check this implementation works with CASA5?

**Comment by sphemakh** [comment]
> Reminder @SpheMakh -- could you please check this implementation works with CASA5?

It creates even more parsing problems. But this latest solution works for CASA >=4.7, 5, and 6

**Comment by o-smirnov** [comment]
Ha, so simple in the end! All right, let's merge.

**Review by o-smirnov — APPROVED** [review]
LGTM.

**Pull request merged**
