### PR TITLE
Add recursive finder for filelike objects

### PR DESCRIPTION
**Pull request by JSKenyon**
(Hopefully) does what it says on the tin. As @o-smirnov points out, this may be somewhat error prone. That said, I have added a handful of tests and the pipeline which originally identified the problem now runs through. In principle, the code could be further refined (the `typeguard` package seems to be very useful), but I think that this should be enough for now. If more exotic types foil this approach, we can always add them to the test suite and iterate.

### CODE REVIEW

**Comment by JSKenyon** [comment]
Requires #268.

**Comment by JSKenyon** [comment]
@o-smirnov Tests are now passing (rebased on master after dropping 3.7). Feel free to add/change at your leisure.

**Comment by o-smirnov** [comment]
OK, I also added the following option to allow explicit user-specified binding of directories. Simple enough change.

```yml
opts:
  backend:
    singularity:
      bind_dirs:
        ~/tmp: rw
        /tmp: ro 
```

@JSKenyon if the pipeline is in front of you now, could you please test this quickly?

**Comment by JSKenyon** [comment]
> @JSKenyon if the pipeline is in front of you now, could you please test this quickly?

In progress. Have disabled my file finder and I am instead mounting everything manually. Will let you know once it runs through.

**Comment by JSKenyon** [comment]
@o-smirnov That seems to have worked. The combination of the finder and the override should be pretty foolproof.

**Review by o-smirnov — APPROVED** [review]
LGTM

**Review by Athanaseus — APPROVED** [review]
Nice!

**Pull request merged**
